#!/bin/sh
# Queue a message

QDIR="$HOME/.smq"

umask 077

mkdir -p "$QDIR" || exit 1
cd "$QDIR" || exit 1

i=0
while test -f "mail$i"; do
	i=`expr $i + 1`
done
MAIL=mail$i

echo "$@" >"$MAIL" || exit 1
cat >"$MAIL" || exit 1
