#!/bin/sh
# Send queued messages

QDIR="$HOME/.smq"

cd "$QDIR" || exit 1
if ! test -f "`ls mail* 2>/dev/null | head -n1`"; then
	echo "no mail in $QDIR"
	exit 0
fi

# process all mails
for m in mail*; do
	if smtp <$m; then
		rm "$m"
		echo "$m sent successfully"
	else
		echo "failed to send $m"
	fi
done
